package View;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import javax.swing.Timer;

/**
 *
 * @author usuario
 */
public class InitialView extends JPanel {
    private static final int TIEMPO = 30;
    private int progreso = 0;
    private Timer timer;
    private JLabel textoDeBienvenida;
    private Image imagenDeFondo;

    /**
     * Creates new customizer InitialView
     */
    public InitialView() {
        
       

        initComponents();

        // Configuración del temporizador
        timer = new Timer(TIEMPO, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                progreso++;
                progressBar.setValue(progreso);

                // Detener el temporizador al alcanzar el 100%
                if (progreso >= progressBar.getMaximum()) {
                    timer.stop();
                    cargaCompletada();
                }
            }
        });
        timer.start();
    }

    /**
     * Acción a realizar cuando la carga se completa.
     */
    public void cargaCompletada() {
       
        
        System.out.println("¡Carga completada!");
    }

    /**
     * Inicializa los componentes de la interfaz.
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        fondo = new javax.swing.JPanel();
        progressBar = new javax.swing.JProgressBar();
        textobienvenida = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLayeredPane1 = new javax.swing.JLayeredPane();

        jMenu1.setText("jMenu1");

        setLayout(new java.awt.GridLayout(1, 0));

        fondo.setBackground(new java.awt.Color(255, 0, 51));
        fondo.setToolTipText("");
        fondo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        fondo.setName(""); // NOI18N
        fondo.setNextFocusableComponent(progressBar);
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        fondo.add(progressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 400, 20));

        textobienvenida.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        textobienvenida.setText("          BIENVENIDO A VELARISHOTEL!!");
        fondo.add(textobienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 500, 120));
        fondo.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, -1));
        fondo.add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        add(fondo);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel fondo;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JLabel textobienvenida;
    // End of variables declaration//GEN-END:variables
}
