/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Beans/Customizer.java to edit this template
 */
package View;

/**
 *
 * @author usuario
 */
public class Pantalladeinicio extends javax.swing.JPanel implements java.beans.Customizer {
    
    private Object bean;

    /**
     * Creates new customizer Pantalladeinicio
     */
    public Pantalladeinicio() {
        initComponents();
    }
    
    public void setObject(Object bean) {
        this.bean = bean;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NOMBREHOTEL = new javax.swing.JButton();
        IDIOMA = new javax.swing.JButton();
        REGISTRO = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        NOMBREHOTEL.setText("VELARISHOTEL");
        NOMBREHOTEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NOMBREHOTELActionPerformed(evt);
            }
        });
        add(NOMBREHOTEL, java.awt.BorderLayout.PAGE_START);

        IDIOMA.setText("IDIOMA");
        add(IDIOMA, java.awt.BorderLayout.CENTER);

        REGISTRO.setText("REGISTRATE");
        REGISTRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGISTROActionPerformed(evt);
            }
        });
        add(REGISTRO, java.awt.BorderLayout.PAGE_END);

        jButton1.setText("INICIAR SESION");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, java.awt.BorderLayout.LINE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void NOMBREHOTELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NOMBREHOTELActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NOMBREHOTELActionPerformed

    private void REGISTROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGISTROActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_REGISTROActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IDIOMA;
    private javax.swing.JButton NOMBREHOTEL;
    private javax.swing.JButton REGISTRO;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
